import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import StoreValue from './StoreValue';
import Header from '../../Skybase-learning/component/Header';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const value = 'basu';
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Header value={value} />
        <h2>my name is {value}</h2>
      </main>
    </>
  );
}
